#ifndef __EYRIE_CALL_H__
#define __EYRIE_CALL_H__

#define RUNTIME_SYSCALL_UNKNOWN             1000
#define RUNTIME_SYSCALL_OCALL               1001
#define RUNTIME_SYSCALL_SHAREDCOPY          1002
#define RUNTIME_SYSCALL_ATTEST_ENCLAVE      1003
#define RUNTIME_SYSCALL_GET_SEALING_KEY     1004
#define RUNTIME_SYSCALL_CREATE_KEYPAIR      1006
#define RUNTIME_SYSCALL_GET_CHAIN           1007
#define RUNTIME_SYSCALL_CRYPTO_INTERFACE    1008
#define RUNTIME_SYSCALL_PRINT_STRING        1009
#define RUNTIME_SYSCALL_EXIT                1101

#define RUNTIME_SYSCALL_WRITE_BUFFER        1109
#define RUNTIME_SYSCALL_READ_BUFFER         1110
#define RUNTIME_SYSCALL_READ_REGISTER       1111
#define RUNTIME_SYSCALL_WRITE_REGISTER      1112

#endif  // __EYRIE_CALL_H__
